version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-demo
    restart: on-failure
    ports:
      - "8888:80"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
